[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/HalaOS/hala-graphics"
version = "0.1.2"

[workspace.dependencies]
# errors
anyhow = "^1"
thiserror = "^1"

# math crates
glam = {version = "^0.25", default-features = false, features = ["serde"]}
libm = "^0.2.7"

# rust log.
log = "^0.4"
pretty_env_logger = "^0.5"

# serde frameworks
serde = {version = "^1.0", default-features = false, features = ["derive"]}
serde_json = "^1.0"

# sub crates.
hala-canvas = {path = "crates/canvas", version = "^0.1"}
