[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/HalaOS/hala-graphics"
version = "0.1.2"

[workspace.dependencies]
# errors
anyhow = "^1"
thiserror = "^1"
# math crates
glam = { version = "^0.28", features = ["serde"] }
libm = "^0.2.7"
# rust log.
log = "^0.4"
pretty_env_logger = "^0.5"
# serde frameworks
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
# graphics
lyon = "^1.0"
winit = "^0.30"
wgpu = "^0.20"
cgmath = "^0.18"
svg = "^0.17"
#futures
futures = "^0.3"
pollster = "^0.3.0"
#utils
bytemuck = "1.16.1"
uuid = "^1.9"
# sub crates.
hala-canvas = { path = "crates/canvas", version = "^0.1" }
