[package]
description = "The hala-canvas rendering backend using wgpu"
edition.workspace = true
name = "hala-canvas-wgpu"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
