// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by protoc 3.19.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `paint.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

// @@protoc_insertion_point(message:paint.Color)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Color {
    // message fields
    // @@protoc_insertion_point(field:paint.Color.r)
    pub r: f64,
    // @@protoc_insertion_point(field:paint.Color.g)
    pub g: f64,
    // @@protoc_insertion_point(field:paint.Color.b)
    pub b: f64,
    // @@protoc_insertion_point(field:paint.Color.a)
    pub a: f64,
    // special fields
    // @@protoc_insertion_point(special_field:paint.Color.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Color {
    fn default() -> &'a Color {
        <Color as ::protobuf::Message>::default_instance()
    }
}

impl Color {
    pub fn new() -> Color {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "r",
            |m: &Color| { &m.r },
            |m: &mut Color| { &mut m.r },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "g",
            |m: &Color| { &m.g },
            |m: &mut Color| { &mut m.g },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "b",
            |m: &Color| { &m.b },
            |m: &mut Color| { &mut m.b },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "a",
            |m: &Color| { &m.a },
            |m: &mut Color| { &mut m.a },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Color>(
            "Color",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Color {
    const NAME: &'static str = "Color";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                9 => {
                    self.r = is.read_double()?;
                },
                17 => {
                    self.g = is.read_double()?;
                },
                25 => {
                    self.b = is.read_double()?;
                },
                33 => {
                    self.a = is.read_double()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.r != 0. {
            my_size += 1 + 8;
        }
        if self.g != 0. {
            my_size += 1 + 8;
        }
        if self.b != 0. {
            my_size += 1 + 8;
        }
        if self.a != 0. {
            my_size += 1 + 8;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.r != 0. {
            os.write_double(1, self.r)?;
        }
        if self.g != 0. {
            os.write_double(2, self.g)?;
        }
        if self.b != 0. {
            os.write_double(3, self.b)?;
        }
        if self.a != 0. {
            os.write_double(4, self.a)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Color {
        Color::new()
    }

    fn clear(&mut self) {
        self.r = 0.;
        self.g = 0.;
        self.b = 0.;
        self.a = 0.;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Color {
        static instance: Color = Color {
            r: 0.,
            g: 0.,
            b: 0.,
            a: 0.,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Color {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Color").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Color {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Color {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:paint.PaintStroke)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PaintStroke {
    // message fields
    // @@protoc_insertion_point(field:paint.PaintStroke.stroke_cap)
    pub stroke_cap: ::protobuf::EnumOrUnknown<StrokeCap>,
    // @@protoc_insertion_point(field:paint.PaintStroke.stroke_join)
    pub stroke_join: ::protobuf::EnumOrUnknown<StrokeJoin>,
    // @@protoc_insertion_point(field:paint.PaintStroke.stroke_miter_limit)
    pub stroke_miter_limit: f32,
    // @@protoc_insertion_point(field:paint.PaintStroke.stroke_width)
    pub stroke_width: f32,
    // special fields
    // @@protoc_insertion_point(special_field:paint.PaintStroke.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PaintStroke {
    fn default() -> &'a PaintStroke {
        <PaintStroke as ::protobuf::Message>::default_instance()
    }
}

impl PaintStroke {
    pub fn new() -> PaintStroke {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "stroke_cap",
            |m: &PaintStroke| { &m.stroke_cap },
            |m: &mut PaintStroke| { &mut m.stroke_cap },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "stroke_join",
            |m: &PaintStroke| { &m.stroke_join },
            |m: &mut PaintStroke| { &mut m.stroke_join },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "stroke_miter_limit",
            |m: &PaintStroke| { &m.stroke_miter_limit },
            |m: &mut PaintStroke| { &mut m.stroke_miter_limit },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "stroke_width",
            |m: &PaintStroke| { &m.stroke_width },
            |m: &mut PaintStroke| { &mut m.stroke_width },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PaintStroke>(
            "PaintStroke",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PaintStroke {
    const NAME: &'static str = "PaintStroke";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.stroke_cap = is.read_enum_or_unknown()?;
                },
                16 => {
                    self.stroke_join = is.read_enum_or_unknown()?;
                },
                29 => {
                    self.stroke_miter_limit = is.read_float()?;
                },
                37 => {
                    self.stroke_width = is.read_float()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.stroke_cap != ::protobuf::EnumOrUnknown::new(StrokeCap::CapButt) {
            my_size += ::protobuf::rt::int32_size(1, self.stroke_cap.value());
        }
        if self.stroke_join != ::protobuf::EnumOrUnknown::new(StrokeJoin::StrokeJoinMiter) {
            my_size += ::protobuf::rt::int32_size(2, self.stroke_join.value());
        }
        if self.stroke_miter_limit != 0. {
            my_size += 1 + 4;
        }
        if self.stroke_width != 0. {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.stroke_cap != ::protobuf::EnumOrUnknown::new(StrokeCap::CapButt) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.stroke_cap))?;
        }
        if self.stroke_join != ::protobuf::EnumOrUnknown::new(StrokeJoin::StrokeJoinMiter) {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.stroke_join))?;
        }
        if self.stroke_miter_limit != 0. {
            os.write_float(3, self.stroke_miter_limit)?;
        }
        if self.stroke_width != 0. {
            os.write_float(4, self.stroke_width)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PaintStroke {
        PaintStroke::new()
    }

    fn clear(&mut self) {
        self.stroke_cap = ::protobuf::EnumOrUnknown::new(StrokeCap::CapButt);
        self.stroke_join = ::protobuf::EnumOrUnknown::new(StrokeJoin::StrokeJoinMiter);
        self.stroke_miter_limit = 0.;
        self.stroke_width = 0.;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PaintStroke {
        static instance: PaintStroke = PaintStroke {
            stroke_cap: ::protobuf::EnumOrUnknown::from_i32(0),
            stroke_join: ::protobuf::EnumOrUnknown::from_i32(0),
            stroke_miter_limit: 0.,
            stroke_width: 0.,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PaintStroke {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PaintStroke").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PaintStroke {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PaintStroke {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:paint.Paint)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Paint {
    // message fields
    // @@protoc_insertion_point(field:paint.Paint.blend_mode)
    pub blend_mode: ::protobuf::EnumOrUnknown<BlendMode>,
    // @@protoc_insertion_point(field:paint.Paint.color)
    pub color: ::protobuf::MessageField<Color>,
    // @@protoc_insertion_point(field:paint.Paint.filter_quality)
    pub filter_quality: ::protobuf::EnumOrUnknown<FilterQuality>,
    // @@protoc_insertion_point(field:paint.Paint.invert_color)
    pub invert_color: bool,
    // @@protoc_insertion_point(field:paint.Paint.is_anti_alias)
    pub is_anti_alias: bool,
    // @@protoc_insertion_point(field:paint.Paint.stroke)
    pub stroke: ::protobuf::MessageField<PaintStroke>,
    // special fields
    // @@protoc_insertion_point(special_field:paint.Paint.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Paint {
    fn default() -> &'a Paint {
        <Paint as ::protobuf::Message>::default_instance()
    }
}

impl Paint {
    pub fn new() -> Paint {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "blend_mode",
            |m: &Paint| { &m.blend_mode },
            |m: &mut Paint| { &mut m.blend_mode },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, Color>(
            "color",
            |m: &Paint| { &m.color },
            |m: &mut Paint| { &mut m.color },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "filter_quality",
            |m: &Paint| { &m.filter_quality },
            |m: &mut Paint| { &mut m.filter_quality },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "invert_color",
            |m: &Paint| { &m.invert_color },
            |m: &mut Paint| { &mut m.invert_color },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "is_anti_alias",
            |m: &Paint| { &m.is_anti_alias },
            |m: &mut Paint| { &mut m.is_anti_alias },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, PaintStroke>(
            "stroke",
            |m: &Paint| { &m.stroke },
            |m: &mut Paint| { &mut m.stroke },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Paint>(
            "Paint",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Paint {
    const NAME: &'static str = "Paint";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.blend_mode = is.read_enum_or_unknown()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.color)?;
                },
                24 => {
                    self.filter_quality = is.read_enum_or_unknown()?;
                },
                32 => {
                    self.invert_color = is.read_bool()?;
                },
                40 => {
                    self.is_anti_alias = is.read_bool()?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.stroke)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.blend_mode != ::protobuf::EnumOrUnknown::new(BlendMode::Clear) {
            my_size += ::protobuf::rt::int32_size(1, self.blend_mode.value());
        }
        if let Some(v) = self.color.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.filter_quality != ::protobuf::EnumOrUnknown::new(FilterQuality::QualityNone) {
            my_size += ::protobuf::rt::int32_size(3, self.filter_quality.value());
        }
        if self.invert_color != false {
            my_size += 1 + 1;
        }
        if self.is_anti_alias != false {
            my_size += 1 + 1;
        }
        if let Some(v) = self.stroke.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.blend_mode != ::protobuf::EnumOrUnknown::new(BlendMode::Clear) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.blend_mode))?;
        }
        if let Some(v) = self.color.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if self.filter_quality != ::protobuf::EnumOrUnknown::new(FilterQuality::QualityNone) {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&self.filter_quality))?;
        }
        if self.invert_color != false {
            os.write_bool(4, self.invert_color)?;
        }
        if self.is_anti_alias != false {
            os.write_bool(5, self.is_anti_alias)?;
        }
        if let Some(v) = self.stroke.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Paint {
        Paint::new()
    }

    fn clear(&mut self) {
        self.blend_mode = ::protobuf::EnumOrUnknown::new(BlendMode::Clear);
        self.color.clear();
        self.filter_quality = ::protobuf::EnumOrUnknown::new(FilterQuality::QualityNone);
        self.invert_color = false;
        self.is_anti_alias = false;
        self.stroke.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Paint {
        static instance: Paint = Paint {
            blend_mode: ::protobuf::EnumOrUnknown::from_i32(0),
            color: ::protobuf::MessageField::none(),
            filter_quality: ::protobuf::EnumOrUnknown::from_i32(0),
            invert_color: false,
            is_anti_alias: false,
            stroke: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Paint {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Paint").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Paint {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Paint {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:paint.BlendMode)
pub enum BlendMode {
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Clear)
    Clear = 0,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Src)
    Src = 2,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Dst)
    Dst = 3,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.SrcOver)
    SrcOver = 4,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.DstOver)
    DstOver = 5,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.SrcIn)
    SrcIn = 6,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.DstIn)
    DstIn = 7,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.SrcOut)
    SrcOut = 8,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.DstOut)
    DstOut = 9,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.SrcATop)
    SrcATop = 10,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.DstATop)
    DstATop = 11,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Xor)
    Xor = 12,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Plus)
    Plus = 13,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Modulate)
    Modulate = 14,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Screen)
    Screen = 15,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Overlay)
    Overlay = 16,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Darken)
    Darken = 17,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Lighten)
    Lighten = 18,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.ColorDodge)
    ColorDodge = 19,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.ColorBurn)
    ColorBurn = 20,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.HardLight)
    HardLight = 21,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.SoftLight)
    SoftLight = 22,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Difference)
    Difference = 23,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Exclusion)
    Exclusion = 24,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Multiply)
    Multiply = 25,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Hue)
    Hue = 26,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Saturation)
    Saturation = 27,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.BlendModeColor)
    BlendModeColor = 28,
    // @@protoc_insertion_point(enum_value:paint.BlendMode.Luminosity)
    Luminosity = 29,
}

impl ::protobuf::Enum for BlendMode {
    const NAME: &'static str = "BlendMode";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<BlendMode> {
        match value {
            0 => ::std::option::Option::Some(BlendMode::Clear),
            2 => ::std::option::Option::Some(BlendMode::Src),
            3 => ::std::option::Option::Some(BlendMode::Dst),
            4 => ::std::option::Option::Some(BlendMode::SrcOver),
            5 => ::std::option::Option::Some(BlendMode::DstOver),
            6 => ::std::option::Option::Some(BlendMode::SrcIn),
            7 => ::std::option::Option::Some(BlendMode::DstIn),
            8 => ::std::option::Option::Some(BlendMode::SrcOut),
            9 => ::std::option::Option::Some(BlendMode::DstOut),
            10 => ::std::option::Option::Some(BlendMode::SrcATop),
            11 => ::std::option::Option::Some(BlendMode::DstATop),
            12 => ::std::option::Option::Some(BlendMode::Xor),
            13 => ::std::option::Option::Some(BlendMode::Plus),
            14 => ::std::option::Option::Some(BlendMode::Modulate),
            15 => ::std::option::Option::Some(BlendMode::Screen),
            16 => ::std::option::Option::Some(BlendMode::Overlay),
            17 => ::std::option::Option::Some(BlendMode::Darken),
            18 => ::std::option::Option::Some(BlendMode::Lighten),
            19 => ::std::option::Option::Some(BlendMode::ColorDodge),
            20 => ::std::option::Option::Some(BlendMode::ColorBurn),
            21 => ::std::option::Option::Some(BlendMode::HardLight),
            22 => ::std::option::Option::Some(BlendMode::SoftLight),
            23 => ::std::option::Option::Some(BlendMode::Difference),
            24 => ::std::option::Option::Some(BlendMode::Exclusion),
            25 => ::std::option::Option::Some(BlendMode::Multiply),
            26 => ::std::option::Option::Some(BlendMode::Hue),
            27 => ::std::option::Option::Some(BlendMode::Saturation),
            28 => ::std::option::Option::Some(BlendMode::BlendModeColor),
            29 => ::std::option::Option::Some(BlendMode::Luminosity),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<BlendMode> {
        match str {
            "Clear" => ::std::option::Option::Some(BlendMode::Clear),
            "Src" => ::std::option::Option::Some(BlendMode::Src),
            "Dst" => ::std::option::Option::Some(BlendMode::Dst),
            "SrcOver" => ::std::option::Option::Some(BlendMode::SrcOver),
            "DstOver" => ::std::option::Option::Some(BlendMode::DstOver),
            "SrcIn" => ::std::option::Option::Some(BlendMode::SrcIn),
            "DstIn" => ::std::option::Option::Some(BlendMode::DstIn),
            "SrcOut" => ::std::option::Option::Some(BlendMode::SrcOut),
            "DstOut" => ::std::option::Option::Some(BlendMode::DstOut),
            "SrcATop" => ::std::option::Option::Some(BlendMode::SrcATop),
            "DstATop" => ::std::option::Option::Some(BlendMode::DstATop),
            "Xor" => ::std::option::Option::Some(BlendMode::Xor),
            "Plus" => ::std::option::Option::Some(BlendMode::Plus),
            "Modulate" => ::std::option::Option::Some(BlendMode::Modulate),
            "Screen" => ::std::option::Option::Some(BlendMode::Screen),
            "Overlay" => ::std::option::Option::Some(BlendMode::Overlay),
            "Darken" => ::std::option::Option::Some(BlendMode::Darken),
            "Lighten" => ::std::option::Option::Some(BlendMode::Lighten),
            "ColorDodge" => ::std::option::Option::Some(BlendMode::ColorDodge),
            "ColorBurn" => ::std::option::Option::Some(BlendMode::ColorBurn),
            "HardLight" => ::std::option::Option::Some(BlendMode::HardLight),
            "SoftLight" => ::std::option::Option::Some(BlendMode::SoftLight),
            "Difference" => ::std::option::Option::Some(BlendMode::Difference),
            "Exclusion" => ::std::option::Option::Some(BlendMode::Exclusion),
            "Multiply" => ::std::option::Option::Some(BlendMode::Multiply),
            "Hue" => ::std::option::Option::Some(BlendMode::Hue),
            "Saturation" => ::std::option::Option::Some(BlendMode::Saturation),
            "BlendModeColor" => ::std::option::Option::Some(BlendMode::BlendModeColor),
            "Luminosity" => ::std::option::Option::Some(BlendMode::Luminosity),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [BlendMode] = &[
        BlendMode::Clear,
        BlendMode::Src,
        BlendMode::Dst,
        BlendMode::SrcOver,
        BlendMode::DstOver,
        BlendMode::SrcIn,
        BlendMode::DstIn,
        BlendMode::SrcOut,
        BlendMode::DstOut,
        BlendMode::SrcATop,
        BlendMode::DstATop,
        BlendMode::Xor,
        BlendMode::Plus,
        BlendMode::Modulate,
        BlendMode::Screen,
        BlendMode::Overlay,
        BlendMode::Darken,
        BlendMode::Lighten,
        BlendMode::ColorDodge,
        BlendMode::ColorBurn,
        BlendMode::HardLight,
        BlendMode::SoftLight,
        BlendMode::Difference,
        BlendMode::Exclusion,
        BlendMode::Multiply,
        BlendMode::Hue,
        BlendMode::Saturation,
        BlendMode::BlendModeColor,
        BlendMode::Luminosity,
    ];
}

impl ::protobuf::EnumFull for BlendMode {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("BlendMode").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            BlendMode::Clear => 0,
            BlendMode::Src => 1,
            BlendMode::Dst => 2,
            BlendMode::SrcOver => 3,
            BlendMode::DstOver => 4,
            BlendMode::SrcIn => 5,
            BlendMode::DstIn => 6,
            BlendMode::SrcOut => 7,
            BlendMode::DstOut => 8,
            BlendMode::SrcATop => 9,
            BlendMode::DstATop => 10,
            BlendMode::Xor => 11,
            BlendMode::Plus => 12,
            BlendMode::Modulate => 13,
            BlendMode::Screen => 14,
            BlendMode::Overlay => 15,
            BlendMode::Darken => 16,
            BlendMode::Lighten => 17,
            BlendMode::ColorDodge => 18,
            BlendMode::ColorBurn => 19,
            BlendMode::HardLight => 20,
            BlendMode::SoftLight => 21,
            BlendMode::Difference => 22,
            BlendMode::Exclusion => 23,
            BlendMode::Multiply => 24,
            BlendMode::Hue => 25,
            BlendMode::Saturation => 26,
            BlendMode::BlendModeColor => 27,
            BlendMode::Luminosity => 28,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for BlendMode {
    fn default() -> Self {
        BlendMode::Clear
    }
}

impl BlendMode {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<BlendMode>("BlendMode")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:paint.FilterQuality)
pub enum FilterQuality {
    // @@protoc_insertion_point(enum_value:paint.FilterQuality.QualityNone)
    QualityNone = 0,
    // @@protoc_insertion_point(enum_value:paint.FilterQuality.QualityLow)
    QualityLow = 1,
    // @@protoc_insertion_point(enum_value:paint.FilterQuality.QualityMedium)
    QualityMedium = 2,
    // @@protoc_insertion_point(enum_value:paint.FilterQuality.QualityHight)
    QualityHight = 3,
}

impl ::protobuf::Enum for FilterQuality {
    const NAME: &'static str = "FilterQuality";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<FilterQuality> {
        match value {
            0 => ::std::option::Option::Some(FilterQuality::QualityNone),
            1 => ::std::option::Option::Some(FilterQuality::QualityLow),
            2 => ::std::option::Option::Some(FilterQuality::QualityMedium),
            3 => ::std::option::Option::Some(FilterQuality::QualityHight),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<FilterQuality> {
        match str {
            "QualityNone" => ::std::option::Option::Some(FilterQuality::QualityNone),
            "QualityLow" => ::std::option::Option::Some(FilterQuality::QualityLow),
            "QualityMedium" => ::std::option::Option::Some(FilterQuality::QualityMedium),
            "QualityHight" => ::std::option::Option::Some(FilterQuality::QualityHight),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [FilterQuality] = &[
        FilterQuality::QualityNone,
        FilterQuality::QualityLow,
        FilterQuality::QualityMedium,
        FilterQuality::QualityHight,
    ];
}

impl ::protobuf::EnumFull for FilterQuality {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("FilterQuality").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for FilterQuality {
    fn default() -> Self {
        FilterQuality::QualityNone
    }
}

impl FilterQuality {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<FilterQuality>("FilterQuality")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:paint.StrokeCap)
pub enum StrokeCap {
    // @@protoc_insertion_point(enum_value:paint.StrokeCap.CapButt)
    CapButt = 0,
    // @@protoc_insertion_point(enum_value:paint.StrokeCap.CapRound)
    CapRound = 1,
    // @@protoc_insertion_point(enum_value:paint.StrokeCap.CapSquare)
    CapSquare = 2,
}

impl ::protobuf::Enum for StrokeCap {
    const NAME: &'static str = "StrokeCap";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<StrokeCap> {
        match value {
            0 => ::std::option::Option::Some(StrokeCap::CapButt),
            1 => ::std::option::Option::Some(StrokeCap::CapRound),
            2 => ::std::option::Option::Some(StrokeCap::CapSquare),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<StrokeCap> {
        match str {
            "CapButt" => ::std::option::Option::Some(StrokeCap::CapButt),
            "CapRound" => ::std::option::Option::Some(StrokeCap::CapRound),
            "CapSquare" => ::std::option::Option::Some(StrokeCap::CapSquare),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [StrokeCap] = &[
        StrokeCap::CapButt,
        StrokeCap::CapRound,
        StrokeCap::CapSquare,
    ];
}

impl ::protobuf::EnumFull for StrokeCap {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("StrokeCap").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for StrokeCap {
    fn default() -> Self {
        StrokeCap::CapButt
    }
}

impl StrokeCap {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<StrokeCap>("StrokeCap")
    }
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:paint.StrokeJoin)
pub enum StrokeJoin {
    // @@protoc_insertion_point(enum_value:paint.StrokeJoin.StrokeJoinMiter)
    StrokeJoinMiter = 0,
    // @@protoc_insertion_point(enum_value:paint.StrokeJoin.StrokeJoinRound)
    StrokeJoinRound = 1,
    // @@protoc_insertion_point(enum_value:paint.StrokeJoin.StrokeJoinBevel)
    StrokeJoinBevel = 2,
}

impl ::protobuf::Enum for StrokeJoin {
    const NAME: &'static str = "StrokeJoin";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<StrokeJoin> {
        match value {
            0 => ::std::option::Option::Some(StrokeJoin::StrokeJoinMiter),
            1 => ::std::option::Option::Some(StrokeJoin::StrokeJoinRound),
            2 => ::std::option::Option::Some(StrokeJoin::StrokeJoinBevel),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<StrokeJoin> {
        match str {
            "StrokeJoinMiter" => ::std::option::Option::Some(StrokeJoin::StrokeJoinMiter),
            "StrokeJoinRound" => ::std::option::Option::Some(StrokeJoin::StrokeJoinRound),
            "StrokeJoinBevel" => ::std::option::Option::Some(StrokeJoin::StrokeJoinBevel),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [StrokeJoin] = &[
        StrokeJoin::StrokeJoinMiter,
        StrokeJoin::StrokeJoinRound,
        StrokeJoin::StrokeJoinBevel,
    ];
}

impl ::protobuf::EnumFull for StrokeJoin {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("StrokeJoin").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for StrokeJoin {
    fn default() -> Self {
        StrokeJoin::StrokeJoinMiter
    }
}

impl StrokeJoin {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<StrokeJoin>("StrokeJoin")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bpaint.proto\x12\x05paint\"?\n\x05Color\x12\x0c\n\x01r\x18\x01\x20\
    \x01(\x01R\x01r\x12\x0c\n\x01g\x18\x02\x20\x01(\x01R\x01g\x12\x0c\n\x01b\
    \x18\x03\x20\x01(\x01R\x01b\x12\x0c\n\x01a\x18\x04\x20\x01(\x01R\x01a\"\
    \xc3\x01\n\x0bPaintStroke\x12/\n\nstroke_cap\x18\x01\x20\x01(\x0e2\x10.p\
    aint.StrokeCapR\tstrokeCap\x122\n\x0bstroke_join\x18\x02\x20\x01(\x0e2\
    \x11.paint.StrokeJoinR\nstrokeJoin\x12,\n\x12stroke_miter_limit\x18\x03\
    \x20\x01(\x02R\x10strokeMiterLimit\x12!\n\x0cstroke_width\x18\x04\x20\
    \x01(\x02R\x0bstrokeWidth\"\x9c\x02\n\x05Paint\x12/\n\nblend_mode\x18\
    \x01\x20\x01(\x0e2\x10.paint.BlendModeR\tblendMode\x12\"\n\x05color\x18\
    \x02\x20\x01(\x0b2\x0c.paint.ColorR\x05color\x12;\n\x0efilter_quality\
    \x18\x03\x20\x01(\x0e2\x14.paint.FilterQualityR\rfilterQuality\x12!\n\
    \x0cinvert_color\x18\x04\x20\x01(\x08R\x0binvertColor\x12\"\n\ris_anti_a\
    lias\x18\x05\x20\x01(\x08R\x0bisAntiAlias\x12/\n\x06stroke\x18\x06\x20\
    \x01(\x0b2\x12.paint.PaintStrokeH\0R\x06stroke\x88\x01\x01B\t\n\x07_stro\
    ke*\x84\x03\n\tBlendMode\x12\t\n\x05Clear\x10\0\x12\x07\n\x03Src\x10\x02\
    \x12\x07\n\x03Dst\x10\x03\x12\x0b\n\x07SrcOver\x10\x04\x12\x0b\n\x07DstO\
    ver\x10\x05\x12\t\n\x05SrcIn\x10\x06\x12\t\n\x05DstIn\x10\x07\x12\n\n\
    \x06SrcOut\x10\x08\x12\n\n\x06DstOut\x10\t\x12\x0b\n\x07SrcATop\x10\n\
    \x12\x0b\n\x07DstATop\x10\x0b\x12\x07\n\x03Xor\x10\x0c\x12\x08\n\x04Plus\
    \x10\r\x12\x0c\n\x08Modulate\x10\x0e\x12\n\n\x06Screen\x10\x0f\x12\x0b\n\
    \x07Overlay\x10\x10\x12\n\n\x06Darken\x10\x11\x12\x0b\n\x07Lighten\x10\
    \x12\x12\x0e\n\nColorDodge\x10\x13\x12\r\n\tColorBurn\x10\x14\x12\r\n\tH\
    ardLight\x10\x15\x12\r\n\tSoftLight\x10\x16\x12\x0e\n\nDifference\x10\
    \x17\x12\r\n\tExclusion\x10\x18\x12\x0c\n\x08Multiply\x10\x19\x12\x07\n\
    \x03Hue\x10\x1a\x12\x0e\n\nSaturation\x10\x1b\x12\x12\n\x0eBlendModeColo\
    r\x10\x1c\x12\x0e\n\nLuminosity\x10\x1d*U\n\rFilterQuality\x12\x0f\n\x0b\
    QualityNone\x10\0\x12\x0e\n\nQualityLow\x10\x01\x12\x11\n\rQualityMedium\
    \x10\x02\x12\x10\n\x0cQualityHight\x10\x03*5\n\tStrokeCap\x12\x0b\n\x07C\
    apButt\x10\0\x12\x0c\n\x08CapRound\x10\x01\x12\r\n\tCapSquare\x10\x02*K\
    \n\nStrokeJoin\x12\x13\n\x0fStrokeJoinMiter\x10\0\x12\x13\n\x0fStrokeJoi\
    nRound\x10\x01\x12\x13\n\x0fStrokeJoinBevel\x10\x02b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(Color::generated_message_descriptor_data());
            messages.push(PaintStroke::generated_message_descriptor_data());
            messages.push(Paint::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(4);
            enums.push(BlendMode::generated_enum_descriptor_data());
            enums.push(FilterQuality::generated_enum_descriptor_data());
            enums.push(StrokeCap::generated_enum_descriptor_data());
            enums.push(StrokeJoin::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
