// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by protoc 3.19.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `text.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

// @@protoc_insertion_point(message:text.Paragraph)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Paragraph {
    // message fields
    // @@protoc_insertion_point(field:text.Paragraph.alphabetic_baseline)
    pub alphabetic_baseline: f32,
    // @@protoc_insertion_point(field:text.Paragraph.did_exceed_max_lines)
    pub did_exceed_max_lines: f32,
    // @@protoc_insertion_point(field:text.Paragraph.height)
    pub height: f32,
    // @@protoc_insertion_point(field:text.Paragraph.ideo_graphic_baseline)
    pub ideo_graphic_baseline: f32,
    // @@protoc_insertion_point(field:text.Paragraph.longest_line)
    pub longest_line: f32,
    // @@protoc_insertion_point(field:text.Paragraph.max_intrinsic_with)
    pub max_intrinsic_with: f32,
    // @@protoc_insertion_point(field:text.Paragraph.min_intrinsic_width)
    pub min_intrinsic_width: f32,
    // @@protoc_insertion_point(field:text.Paragraph.width)
    pub width: f32,
    // special fields
    // @@protoc_insertion_point(special_field:text.Paragraph.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Paragraph {
    fn default() -> &'a Paragraph {
        <Paragraph as ::protobuf::Message>::default_instance()
    }
}

impl Paragraph {
    pub fn new() -> Paragraph {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "alphabetic_baseline",
            |m: &Paragraph| { &m.alphabetic_baseline },
            |m: &mut Paragraph| { &mut m.alphabetic_baseline },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "did_exceed_max_lines",
            |m: &Paragraph| { &m.did_exceed_max_lines },
            |m: &mut Paragraph| { &mut m.did_exceed_max_lines },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "height",
            |m: &Paragraph| { &m.height },
            |m: &mut Paragraph| { &mut m.height },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "ideo_graphic_baseline",
            |m: &Paragraph| { &m.ideo_graphic_baseline },
            |m: &mut Paragraph| { &mut m.ideo_graphic_baseline },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "longest_line",
            |m: &Paragraph| { &m.longest_line },
            |m: &mut Paragraph| { &mut m.longest_line },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "max_intrinsic_with",
            |m: &Paragraph| { &m.max_intrinsic_with },
            |m: &mut Paragraph| { &mut m.max_intrinsic_with },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "min_intrinsic_width",
            |m: &Paragraph| { &m.min_intrinsic_width },
            |m: &mut Paragraph| { &mut m.min_intrinsic_width },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "width",
            |m: &Paragraph| { &m.width },
            |m: &mut Paragraph| { &mut m.width },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Paragraph>(
            "Paragraph",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Paragraph {
    const NAME: &'static str = "Paragraph";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.alphabetic_baseline = is.read_float()?;
                },
                21 => {
                    self.did_exceed_max_lines = is.read_float()?;
                },
                29 => {
                    self.height = is.read_float()?;
                },
                37 => {
                    self.ideo_graphic_baseline = is.read_float()?;
                },
                45 => {
                    self.longest_line = is.read_float()?;
                },
                53 => {
                    self.max_intrinsic_with = is.read_float()?;
                },
                61 => {
                    self.min_intrinsic_width = is.read_float()?;
                },
                69 => {
                    self.width = is.read_float()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.alphabetic_baseline != 0. {
            my_size += 1 + 4;
        }
        if self.did_exceed_max_lines != 0. {
            my_size += 1 + 4;
        }
        if self.height != 0. {
            my_size += 1 + 4;
        }
        if self.ideo_graphic_baseline != 0. {
            my_size += 1 + 4;
        }
        if self.longest_line != 0. {
            my_size += 1 + 4;
        }
        if self.max_intrinsic_with != 0. {
            my_size += 1 + 4;
        }
        if self.min_intrinsic_width != 0. {
            my_size += 1 + 4;
        }
        if self.width != 0. {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.alphabetic_baseline != 0. {
            os.write_float(1, self.alphabetic_baseline)?;
        }
        if self.did_exceed_max_lines != 0. {
            os.write_float(2, self.did_exceed_max_lines)?;
        }
        if self.height != 0. {
            os.write_float(3, self.height)?;
        }
        if self.ideo_graphic_baseline != 0. {
            os.write_float(4, self.ideo_graphic_baseline)?;
        }
        if self.longest_line != 0. {
            os.write_float(5, self.longest_line)?;
        }
        if self.max_intrinsic_with != 0. {
            os.write_float(6, self.max_intrinsic_with)?;
        }
        if self.min_intrinsic_width != 0. {
            os.write_float(7, self.min_intrinsic_width)?;
        }
        if self.width != 0. {
            os.write_float(8, self.width)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Paragraph {
        Paragraph::new()
    }

    fn clear(&mut self) {
        self.alphabetic_baseline = 0.;
        self.did_exceed_max_lines = 0.;
        self.height = 0.;
        self.ideo_graphic_baseline = 0.;
        self.longest_line = 0.;
        self.max_intrinsic_with = 0.;
        self.min_intrinsic_width = 0.;
        self.width = 0.;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Paragraph {
        static instance: Paragraph = Paragraph {
            alphabetic_baseline: 0.,
            did_exceed_max_lines: 0.,
            height: 0.,
            ideo_graphic_baseline: 0.,
            longest_line: 0.,
            max_intrinsic_with: 0.,
            min_intrinsic_width: 0.,
            width: 0.,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Paragraph {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Paragraph").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Paragraph {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Paragraph {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\ntext.proto\x12\x04text\"\xd0\x02\n\tParagraph\x12/\n\x13alphabetic_b\
    aseline\x18\x01\x20\x01(\x02R\x12alphabeticBaseline\x12/\n\x14did_exceed\
    _max_lines\x18\x02\x20\x01(\x02R\x11didExceedMaxLines\x12\x16\n\x06heigh\
    t\x18\x03\x20\x01(\x02R\x06height\x122\n\x15ideo_graphic_baseline\x18\
    \x04\x20\x01(\x02R\x13ideoGraphicBaseline\x12!\n\x0clongest_line\x18\x05\
    \x20\x01(\x02R\x0blongestLine\x12,\n\x12max_intrinsic_with\x18\x06\x20\
    \x01(\x02R\x10maxIntrinsicWith\x12.\n\x13min_intrinsic_width\x18\x07\x20\
    \x01(\x02R\x11minIntrinsicWidth\x12\x14\n\x05width\x18\x08\x20\x01(\x02R\
    \x05widthb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Paragraph::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
