// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by protoc 3.19.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `canvas.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

// @@protoc_insertion_point(message:hala.canvas.OpCode)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct OpCode {
    // message oneof groups
    pub code: ::std::option::Option<op_code::Code>,
    // special fields
    // @@protoc_insertion_point(special_field:hala.canvas.OpCode.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a OpCode {
    fn default() -> &'a OpCode {
        <OpCode as ::protobuf::Message>::default_instance()
    }
}

impl OpCode {
    pub fn new() -> OpCode {
        ::std::default::Default::default()
    }

    // .hala.canvas.Scale scale = 1;

    pub fn scale(&self) -> &Scale {
        match self.code {
            ::std::option::Option::Some(op_code::Code::Scale(ref v)) => v,
            _ => <Scale as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_scale(&mut self) {
        self.code = ::std::option::Option::None;
    }

    pub fn has_scale(&self) -> bool {
        match self.code {
            ::std::option::Option::Some(op_code::Code::Scale(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_scale(&mut self, v: Scale) {
        self.code = ::std::option::Option::Some(op_code::Code::Scale(v))
    }

    // Mutable pointer to the field.
    pub fn mut_scale(&mut self) -> &mut Scale {
        if let ::std::option::Option::Some(op_code::Code::Scale(_)) = self.code {
        } else {
            self.code = ::std::option::Option::Some(op_code::Code::Scale(Scale::new()));
        }
        match self.code {
            ::std::option::Option::Some(op_code::Code::Scale(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_scale(&mut self) -> Scale {
        if self.has_scale() {
            match self.code.take() {
                ::std::option::Option::Some(op_code::Code::Scale(v)) => v,
                _ => panic!(),
            }
        } else {
            Scale::new()
        }
    }

    // .hala.canvas.Skew skew = 2;

    pub fn skew(&self) -> &Skew {
        match self.code {
            ::std::option::Option::Some(op_code::Code::Skew(ref v)) => v,
            _ => <Skew as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_skew(&mut self) {
        self.code = ::std::option::Option::None;
    }

    pub fn has_skew(&self) -> bool {
        match self.code {
            ::std::option::Option::Some(op_code::Code::Skew(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_skew(&mut self, v: Skew) {
        self.code = ::std::option::Option::Some(op_code::Code::Skew(v))
    }

    // Mutable pointer to the field.
    pub fn mut_skew(&mut self) -> &mut Skew {
        if let ::std::option::Option::Some(op_code::Code::Skew(_)) = self.code {
        } else {
            self.code = ::std::option::Option::Some(op_code::Code::Skew(Skew::new()));
        }
        match self.code {
            ::std::option::Option::Some(op_code::Code::Skew(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_skew(&mut self) -> Skew {
        if self.has_skew() {
            match self.code.take() {
                ::std::option::Option::Some(op_code::Code::Skew(v)) => v,
                _ => panic!(),
            }
        } else {
            Skew::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, Scale>(
            "scale",
            OpCode::has_scale,
            OpCode::scale,
            OpCode::mut_scale,
            OpCode::set_scale,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, Skew>(
            "skew",
            OpCode::has_skew,
            OpCode::skew,
            OpCode::mut_skew,
            OpCode::set_skew,
        ));
        oneofs.push(op_code::Code::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<OpCode>(
            "OpCode",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for OpCode {
    const NAME: &'static str = "OpCode";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.code = ::std::option::Option::Some(op_code::Code::Scale(is.read_message()?));
                },
                18 => {
                    self.code = ::std::option::Option::Some(op_code::Code::Skew(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.code {
            match v {
                &op_code::Code::Scale(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &op_code::Code::Skew(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.code {
            match v {
                &op_code::Code::Scale(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
                },
                &op_code::Code::Skew(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> OpCode {
        OpCode::new()
    }

    fn clear(&mut self) {
        self.code = ::std::option::Option::None;
        self.code = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static OpCode {
        static instance: OpCode = OpCode {
            code: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for OpCode {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("OpCode").unwrap()).clone()
    }
}

impl ::std::fmt::Display for OpCode {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OpCode {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `OpCode`
pub mod op_code {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:hala.canvas.OpCode.code)
    pub enum Code {
        // @@protoc_insertion_point(oneof_field:hala.canvas.OpCode.scale)
        Scale(super::Scale),
        // @@protoc_insertion_point(oneof_field:hala.canvas.OpCode.skew)
        Skew(super::Skew),
    }

    impl ::protobuf::Oneof for Code {
    }

    impl ::protobuf::OneofFull for Code {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::OpCode as ::protobuf::MessageFull>::descriptor().oneof_by_name("code").unwrap()).clone()
        }
    }

    impl Code {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Code>("code")
        }
    }
}

// @@protoc_insertion_point(message:hala.canvas.Scale)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Scale {
    // message fields
    // @@protoc_insertion_point(field:hala.canvas.Scale.sx)
    pub sx: f32,
    // @@protoc_insertion_point(field:hala.canvas.Scale.sy)
    pub sy: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:hala.canvas.Scale.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Scale {
    fn default() -> &'a Scale {
        <Scale as ::protobuf::Message>::default_instance()
    }
}

impl Scale {
    pub fn new() -> Scale {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sx",
            |m: &Scale| { &m.sx },
            |m: &mut Scale| { &mut m.sx },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "sy",
            |m: &Scale| { &m.sy },
            |m: &mut Scale| { &mut m.sy },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Scale>(
            "Scale",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Scale {
    const NAME: &'static str = "Scale";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.sx = is.read_float()?;
                },
                21 => {
                    self.sy = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.sx != 0. {
            my_size += 1 + 4;
        }
        if let Some(v) = self.sy {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.sx != 0. {
            os.write_float(1, self.sx)?;
        }
        if let Some(v) = self.sy {
            os.write_float(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Scale {
        Scale::new()
    }

    fn clear(&mut self) {
        self.sx = 0.;
        self.sy = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Scale {
        static instance: Scale = Scale {
            sx: 0.,
            sy: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Scale {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Scale").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Scale {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Scale {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:hala.canvas.Skew)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Skew {
    // message fields
    // @@protoc_insertion_point(field:hala.canvas.Skew.sx)
    pub sx: f32,
    // @@protoc_insertion_point(field:hala.canvas.Skew.sy)
    pub sy: f32,
    // special fields
    // @@protoc_insertion_point(special_field:hala.canvas.Skew.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Skew {
    fn default() -> &'a Skew {
        <Skew as ::protobuf::Message>::default_instance()
    }
}

impl Skew {
    pub fn new() -> Skew {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sx",
            |m: &Skew| { &m.sx },
            |m: &mut Skew| { &mut m.sx },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sy",
            |m: &Skew| { &m.sy },
            |m: &mut Skew| { &mut m.sy },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Skew>(
            "Skew",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Skew {
    const NAME: &'static str = "Skew";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.sx = is.read_float()?;
                },
                21 => {
                    self.sy = is.read_float()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.sx != 0. {
            my_size += 1 + 4;
        }
        if self.sy != 0. {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.sx != 0. {
            os.write_float(1, self.sx)?;
        }
        if self.sy != 0. {
            os.write_float(2, self.sy)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Skew {
        Skew::new()
    }

    fn clear(&mut self) {
        self.sx = 0.;
        self.sy = 0.;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Skew {
        static instance: Skew = Skew {
            sx: 0.,
            sy: 0.,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Skew {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Skew").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Skew {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Skew {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:hala.canvas.ClipOp)
pub enum ClipOp {
    // @@protoc_insertion_point(enum_value:hala.canvas.ClipOp.Difference)
    Difference = 0,
    // @@protoc_insertion_point(enum_value:hala.canvas.ClipOp.Intersect)
    Intersect = 1,
}

impl ::protobuf::Enum for ClipOp {
    const NAME: &'static str = "ClipOp";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<ClipOp> {
        match value {
            0 => ::std::option::Option::Some(ClipOp::Difference),
            1 => ::std::option::Option::Some(ClipOp::Intersect),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<ClipOp> {
        match str {
            "Difference" => ::std::option::Option::Some(ClipOp::Difference),
            "Intersect" => ::std::option::Option::Some(ClipOp::Intersect),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [ClipOp] = &[
        ClipOp::Difference,
        ClipOp::Intersect,
    ];
}

impl ::protobuf::EnumFull for ClipOp {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("ClipOp").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for ClipOp {
    fn default() -> Self {
        ClipOp::Difference
    }
}

impl ClipOp {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<ClipOp>("ClipOp")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0ccanvas.proto\x12\x0bhala.canvas\"e\n\x06OpCode\x12*\n\x05scale\x18\
    \x01\x20\x01(\x0b2\x12.hala.canvas.ScaleH\0R\x05scale\x12'\n\x04skew\x18\
    \x02\x20\x01(\x0b2\x11.hala.canvas.SkewH\0R\x04skewB\x06\n\x04code\"3\n\
    \x05Scale\x12\x0e\n\x02sx\x18\x01\x20\x01(\x02R\x02sx\x12\x13\n\x02sy\
    \x18\x02\x20\x01(\x02H\0R\x02sy\x88\x01\x01B\x05\n\x03_sy\"&\n\x04Skew\
    \x12\x0e\n\x02sx\x18\x01\x20\x01(\x02R\x02sx\x12\x0e\n\x02sy\x18\x02\x20\
    \x01(\x02R\x02sy*'\n\x06ClipOp\x12\x0e\n\nDifference\x10\0\x12\r\n\tInte\
    rsect\x10\x01b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(OpCode::generated_message_descriptor_data());
            messages.push(Scale::generated_message_descriptor_data());
            messages.push(Skew::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(ClipOp::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
